version: '2'

services:
  tarantool:
    container_name: tarantool_ski_resort
    image: tarantool/tarantool:1.7
    command: tarantool /usr/local/share/tarantool/app.init.lua
    ports:
      - 3301:3301
    volumes:
      - c:/BMSTU_6sem_software_design/src/tarantool/app:/usr/local/share/tarantool
      - c:/BMSTU_6sem_software_design/src/tarantool/data:/var/lib/tarantool